<?php

namespace pantera\discussions;

use yii\base\InvalidConfigException;
use yii\base\Module as YiiModule;

class Module extends YiiModule {

    public $identityModel = 'common\models\User';

    public $access = ['@'];
    public $deleteAccess = ['admin'];
    public $userModel = null;
    public $userAvatarPropertity = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function isCanDelete() {
        foreach ($this->deleteAccess as $access) {
            if(\Yii::$app->user->can($access)) return true;
        }
        return false;
    }

    public function getMenuItems()
    {
        return [['label' => 'Обсуждения', 'url' => ['/discussion'], 'icon' => 'comments', 'active' => \Yii::$app->controller->module->id == 'discussion']];
    }
}
